### ISSUE TITLE
Verse version is unclear

### ISSUE THREAD

**Issue by 10Dev** [fDero/Verse#1]
It isn't clear in your readme if you are working towards conformance with the official Verse language from Epic Games or not. It would be great if you are since the only current implementation is in the UEFN editor and a stand alone compiler would be very useful.

For information see: 

https://github.com/VerseMetaVerse/VerseInfo
https://www.youtube.com/watch?v=OJv8rFap0Nw

**Comment by fDero** [comment]
No, i'm creating a whole new language from scracth. I believe my repository was created a few months before the Epic Games programming language was released. To avoid confusion i will probably change the of the language name anyway.
